### PR TITLE
Remove already-gitignored .idea directory

### PR DESCRIPTION
**Pull request by jaceklaskowski**
Looks like the `.idea` directory got committed anyway. Removing the cruft.

### CODE REVIEW

**Comment by thunterdb** [comment]
Merging, thanks!

**Comment by thunterdb** [comment]
@jaceklaskowski can you merge again with master to trigger a build? I am unable to trigger a manual build.

**Comment by jaceklaskowski** [comment]
I need some help to do it. "merge again with master" -- I don't get that part.

**Comment by thunterdb** [comment]
Oh, I meant to say that you should do a git pull databricks master to pull
the latest changes from your other PR that just got merged and then push
the changes to gitignore-idea




On August 11, 2016 at 11:31:20 AM, Jacek Laskowski (notifications@github.com)
wrote:

I need some help to do it. "merge again with master" -- I don't get that
part.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/databricks/tensorframes/pull/53#issuecomment-239249418>,
or mute the thread

**Comment by jaceklaskowski** [comment]
Thanks for your help. I was doing rebase against my own master and that's why I couldn't understanding what's happening. With your help and adding databricks' remote repo, I did the changes. Thanks!

**Comment by jaceklaskowski** [comment]
A friendly reminder for @thunterdb about the PR... :)

**Comment by thunterdb** [comment]
@jaceklaskowski thanks for the cleanup!

**Pull request merged**
