### PR TITLE
Up Tensorframes version to 0.2.9 in preparation for release

### PR DESCRIPTION
**Pull request by smurching**
This PR bumps the tensorframes version to 0.2.9 in preparation for a new release.

### CODE REVIEW

**Comment by smurching** [comment]
Here's a possible set of release notes for 0.2.9:

This is the final release for 0.2.9.

Notable changes since 0.2.8:

* Upgrades tensorflow dependency from version 1.1.0 to 1.3.0
* Adds `map_blocks`, `map_row` APIs for Pandas DataFrames 
* Adds support for tensorflow variables

**Comment by thunterdb** [comment]
@smurching merging, thank you!

**Comment by thunterdb** [comment]
@smurching can you also publish the new version to spark-packages too?

**Comment by smurching** [comment]
@thunterdb yep, they're up now! https://spark-packages.org/package/databricks/tensorframes

**Pull request merged**
