### PR TITLE
Update version numbers from 0.2.8 to 0.2.9-rc0 for release

### PR DESCRIPTION
**Pull request by smurching**
Update all version numbers in Tensorframes from 0.2.8 to 0.2.9-rc0 in preparation for release.

### CODE REVIEW

**Comment by smurching** [comment]
Once this is merged, should I push the new git tag (v0.2.9rc-0) to upstream?

**Comment by thunterdb** [comment]
@smurching yes, once this is merged, you can push the tag and build the artifacts.

**Comment by thunterdb** [comment]
@smurching it is merged.

**Comment by smurching** [comment]
Thanks!

**Pull request merged**
